### ISSUE TITLE
Required fields

### ISSUE THREAD

**Issue by jantbox** [protonemedia/laravel-form-components#45]
When developing forms it is common to mark the required fields to differentiate them from the rest. In many cases a red asterisk is used behind the label.

I think it would be nice to add a way to identify these fields. Here is a simple way to implement it:
A "required" tag (`<x-form-input name = "name" required />`) could generate this code:

```
<div class = "form-group">
  <label for = "auto_id_name" class = "required"> Name </label>
  <div class = "input-group">
    <input class = "form-control" type = "text" name = "name" value = "" id = "auto_id_name" required>
  </div>
</div>
```

The appearance of the label can be controlled by CSS (label.required) and optionally the "required" modifier in the input tag can help with data validation.

**Comment by mvd81** [comment]
+1, got a small workarround for now,

After publishing the configuration file and Blade views
Change the input, select etc.

Add the $attributes
`<x-form-label :label="$label" :for="$attributes->get('id') ?: $id()" :attributes="$attributes" />`

In the label component:

```
<label {!! $attributes !!}>
        {{ $label }}

        @if($attributes->get('req'))
            <span class="required">*</span>
        @endif
    </label>`
```

So now you can set 'required' fields
`<x-form-input name="name" req="required"/>`

I am using 'req' on purpose because I make use of Livewire (and some Livewire fields are without defer and immediately give an error).

**Comment by pascalbaljet** [comment]
I'm closing this issue as I don't want to support this in the package. Every project has a different way of handling these requirements, and the package can be customized and extended quite easily.
